package com.faqchatbot;

import javafx.animation.*;
import javafx.application.Platform;
import javafx.geometry.*;
import javafx.scene.control.*;
import javafx.scene.image.*;
import javafx.scene.input.*;
import javafx.scene.layout.*;
import javafx.scene.paint.*;
import javafx.scene.shape.Rectangle;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.util.Duration;

import java.io.File;

/**
 * ChatController — Enhanced with all 10 features:
 *
 *  1  Voice Input        – Mic button records & transcribes via Whisper
 *  2  Image Upload       – JPEG/PNG uploaded, base64-sent to Groq vision
 *  3  Chat Search        – Ctrl+F / search button opens ChatSearchPanel
 *  4  Pin Messages       – Pin button on ChatBubble + Pinned panel button
 *  5  Auto Title         – Session title auto-generated by AI after first reply
 *  6  Notification Sound – NotificationSoundManager.ping() on AI response
 *  7  Word count         – Implemented inside ChatBubble
 *  8  Animated gradient  – CSS-animated gradient strip in header
 *  9  Multi-language UI  – All labels use I18nManager.t()
 * 10  Keyboard shortcuts – Global key handler + KeyboardShortcutsPanel
 */
public class ChatController extends VBox {

    private ScrollPane scrollPane;
    private VBox chatArea;
    private TextArea inputField;
    private Button sendButton;
    private Button clearButton;
    private Button exportButton;
    private Button uploadButton;
    private Button settingsButton;
    private Button regenerateButton;
    private Button pinnedButton;      // Feature 4
    private Button searchButton;      // Feature 3
    private Button micButton;         // Feature 1
    private Label charCountLabel;
    private Label statusLabel;
    private Label modelLabel;
    private Pane gradientStrip;       // Feature 8
    private GroqClient groqClient;
    private ChatSession currentSession;
    private Sidebar sidebar;
    private Stage primaryStage;

    // Feature 1: mic state
    private boolean micRecording = false;

    public ChatController(Stage primaryStage) {
        super();
        this.primaryStage = primaryStage;
        this.groqClient   = new GroqClient();
        this.currentSession = SessionManager.createNewSession();
        buildUI();
        registerGlobalShortcuts(); // Feature 10
        showWelcomeMessage();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // UI CONSTRUCTION
    // ═════════════════════════════════════════════════════════════════════════
    private void buildUI() {

        // ── Feature 8: Animated gradient strip ────────────────────────────────
        gradientStrip = new Pane();
        gradientStrip.setPrefHeight(3);
        gradientStrip.setMaxWidth(Double.MAX_VALUE);
        gradientStrip.getStyleClass().add("gradient-strip");
        animateGradientStrip();

        // ── HEADER ────────────────────────────────────────────────────────────
        HBox header = new HBox();
        header.getStyleClass().add("chat-header");
        header.setAlignment(Pos.CENTER_LEFT);
        header.setPadding(new Insets(14, 20, 14, 20));
        header.setSpacing(10);

        Label headerIcon = new Label("🤖");
        headerIcon.getStyleClass().add("header-icon");

        VBox headerText = new VBox(2);
        Label headerTitle = new Label(I18nManager.t("app.title"));    // Feature 9
        headerTitle.getStyleClass().add("header-title");
        modelLabel = new Label("Model: " + groqClient.getCurrentModel()
                + "  ·  Persona: " + groqClient.getCurrentPersona());
        modelLabel.getStyleClass().add("header-subtitle");
        headerText.getChildren().addAll(headerTitle, modelLabel);

        // Status
        HBox statusBox = new HBox(5);
        statusBox.setAlignment(Pos.CENTER);
        Label statusDot = new Label("●");
        statusDot.getStyleClass().add("status-dot");
        statusLabel = new Label(I18nManager.t("header.online"));       // Feature 9
        statusLabel.getStyleClass().add("status-text");
        statusBox.getChildren().addAll(statusDot, statusLabel);

        // Header buttons
        settingsButton = iconBtn("⚙️", I18nManager.t("btn.settings"), e -> openSettings());
        exportButton   = iconBtn("📤", I18nManager.t("btn.export"),   e -> showExportMenu());
        clearButton    = iconBtn("🗑",  I18nManager.t("btn.clear"),    e -> clearChat());
        pinnedButton   = iconBtn("📍", I18nManager.t("btn.pinned"),   e -> new PinnedPanel().show()); // Feature 4
        searchButton   = iconBtn("🔍", I18nManager.t("btn.search"),   e -> openSearch());            // Feature 3

        Region spacer = new Region();
        HBox.setHgrow(spacer, Priority.ALWAYS);

        header.getChildren().addAll(headerIcon, headerText, spacer,
                statusBox, searchButton, pinnedButton,
                settingsButton, exportButton, clearButton);

        // ── CHAT AREA ─────────────────────────────────────────────────────────
        chatArea = new VBox(10);
        chatArea.setPadding(new Insets(20, 10, 20, 10));
        chatArea.getStyleClass().add("chat-area");

        scrollPane = new ScrollPane(chatArea);
        scrollPane.setFitToWidth(true);
        scrollPane.getStyleClass().add("chat-scroll");
        scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);
        scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);
        VBox.setVgrow(scrollPane, Priority.ALWAYS);
        chatArea.heightProperty().addListener((obs, ov, nv) -> scrollPane.setVvalue(1.0));

        // ── INPUT AREA ────────────────────────────────────────────────────────
        VBox inputWrapper = new VBox(6);
        inputWrapper.getStyleClass().add("input-wrapper");
        inputWrapper.setPadding(new Insets(12, 16, 12, 16));

        HBox topInputRow = new HBox(8);
        topInputRow.setAlignment(Pos.CENTER_RIGHT);
        charCountLabel = new Label("0 " + I18nManager.t("input.charcount")); // Feature 9
        charCountLabel.getStyleClass().add("char-count");

        regenerateButton = new Button(I18nManager.t("btn.regen"));
        regenerateButton.getStyleClass().add("regen-button");
        regenerateButton.setOnAction(e -> regenerateResponse());

        Region topSpacer = new Region();
        HBox.setHgrow(topSpacer, Priority.ALWAYS);
        topInputRow.getChildren().addAll(regenerateButton, topSpacer, charCountLabel);

        inputField = new TextArea();
        inputField.setPromptText(I18nManager.t("input.placeholder")); // Feature 9
        inputField.getStyleClass().add("input-field");
        inputField.setWrapText(true);
        inputField.setPrefRowCount(2);
        inputField.setMaxHeight(80);
        if (I18nManager.isRTL()) {
            inputField.setNodeOrientation(NodeOrientation.RIGHT_TO_LEFT);
        }

        inputField.textProperty().addListener((obs, ov, nv) -> {
            if (nv.length() > 2000) inputField.setText(ov);
            else charCountLabel.setText(nv.length() + " " + I18nManager.t("input.charcount"));
        });

        inputField.setOnKeyPressed(e -> {
            if (e.getCode() == KeyCode.ENTER && !e.isShiftDown()) {
                e.consume();
                handleSend();
            }
        });

        HBox bottomInputRow = new HBox(8);
        bottomInputRow.setAlignment(Pos.CENTER);

        // Feature 2: Image upload button (broadens existing upload button)
        uploadButton = new Button("📎");
        uploadButton.getStyleClass().add("upload-button");
        uploadButton.setTooltip(new Tooltip(I18nManager.t("btn.upload")));
        uploadButton.setOnAction(e -> handleFileUpload());

        // Feature 1: Mic button
        micButton = new Button(I18nManager.t("btn.mic"));
        micButton.getStyleClass().add("upload-button");
        micButton.setTooltip(new Tooltip("Voice input (Ctrl+M)"));
        micButton.setDisable(!VoiceInputManager.isAvailable());
        micButton.setOnAction(e -> toggleMic());

        Label hintLabel = new Label(I18nManager.t("input.hint")); // Feature 9
        hintLabel.getStyleClass().add("hint-label");

        Region bottomSpacer = new Region();
        HBox.setHgrow(bottomSpacer, Priority.ALWAYS);

        sendButton = new Button(I18nManager.t("input.send")); // Feature 9
        sendButton.getStyleClass().add("send-button");
        sendButton.setOnAction(e -> handleSend());

        bottomInputRow.getChildren().addAll(uploadButton, micButton, hintLabel,
                bottomSpacer, sendButton);

        inputWrapper.getChildren().addAll(topInputRow, inputField, bottomInputRow);

        // ── ASSEMBLE ──────────────────────────────────────────────────────────
        this.getChildren().addAll(gradientStrip, header, scrollPane, inputWrapper);
        this.getStyleClass().add("main-container");
        VBox.setVgrow(scrollPane, Priority.ALWAYS);
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 8: Animated gradient strip
    // ═════════════════════════════════════════════════════════════════════════
    private void animateGradientStrip() {
        // We animate by shifting a CSS-class-driven background-position
        // using a CSS keyframe animation defined in style.css (added below).
        // As a fallback, we also set a JavaFX animated Rectangle fill.
        Rectangle bar = new Rectangle();
        bar.setHeight(3);
        bar.widthProperty().bind(gradientStrip.widthProperty());

        Stop[] stops = {
            new Stop(0.0, Color.web("#1f6feb")),
            new Stop(0.3, Color.web("#a371f7")),
            new Stop(0.6, Color.web("#3fb950")),
            new Stop(1.0, Color.web("#1f6feb"))
        };
        LinearGradient gradient = new LinearGradient(0, 0, 1, 0, true,
                CycleMethod.REFLECT, stops);
        bar.setFill(gradient);
        gradientStrip.getChildren().add(bar);

        // Animate gradient offset by moving the bar left/right
        TranslateTransition tt = new TranslateTransition(Duration.seconds(3), bar);
        tt.setFromX(0);
        tt.setToX(-200);
        tt.setCycleCount(Animation.INDEFINITE);
        tt.setAutoReverse(true);
        tt.play();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 10: Global keyboard shortcuts
    // ═════════════════════════════════════════════════════════════════════════
    private void registerGlobalShortcuts() {
        // Called after the node is added to the scene; we add listener lazily
        this.sceneProperty().addListener((obs, ov, scene) -> {
            if (scene == null) return;
            scene.addEventFilter(KeyEvent.KEY_PRESSED, e -> {
                if (e.isControlDown()) {
                    switch (e.getCode()) {
                        case F -> { e.consume(); openSearch(); }
                        case N -> { e.consume(); clearChat(); }
                        case P -> { e.consume(); new PinnedPanel().show(); }
                        case COMMA -> { e.consume(); openSettings(); }
                        case SLASH -> { e.consume(); new KeyboardShortcutsPanel().show(); }
                        case E -> { e.consume(); showExportMenu(); }
                        case L -> { e.consume(); clearChat(); }
                        case R -> { e.consume(); regenerateResponse(); }
                        case M -> { e.consume(); toggleMic(); }
                        case S -> { e.consume(); toggleNotifSound(); }
                        case T -> {
                            e.consume();
                            SpeechManager.setEnabled(!SpeechManager.isEnabled());
                        }
                        // Language switch – Feature 9
                        case DIGIT1 -> { e.consume(); switchLanguage(I18nManager.Language.ENGLISH); }
                        case DIGIT2 -> { e.consume(); switchLanguage(I18nManager.Language.ARABIC); }
                        case DIGIT3 -> { e.consume(); switchLanguage(I18nManager.Language.URDU); }
                        case DIGIT4 -> { e.consume(); switchLanguage(I18nManager.Language.FRENCH); }
                        default -> {}
                    }
                } else if (e.getCode() == KeyCode.ESCAPE) {
                    if (micRecording) { e.consume(); toggleMic(); }
                }
            });
        });
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 1: Voice Input
    // ═════════════════════════════════════════════════════════════════════════
    private void toggleMic() {
        if (!VoiceInputManager.isAvailable()) return;

        if (!micRecording) {
            boolean started = VoiceInputManager.startRecording();
            if (started) {
                micRecording = true;
                micButton.setText(I18nManager.t("btn.mic.stop"));
                micButton.getStyleClass().add("mic-recording");
                statusLabel.setText("🔴 Recording…");
            }
        } else {
            micRecording = false;
            micButton.setText(I18nManager.t("btn.mic"));
            micButton.getStyleClass().remove("mic-recording");
            statusLabel.setText("Transcribing…");
            VoiceInputManager.stopRecording(text -> Platform.runLater(() -> {
                statusLabel.setText(I18nManager.t("header.online"));
                if (!text.startsWith("⚠️")) {
                    inputField.setText(text);
                    inputField.positionCaret(text.length());
                } else {
                    showAlert("Voice Error", text);
                }
            }));
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 3: Chat Search
    // ═════════════════════════════════════════════════════════════════════════
    private void openSearch() {
        ChatSearchPanel panel = new ChatSearchPanel(session -> {
            loadSession(session);
            if (sidebar != null) sidebar.setActiveSession(session);
        });
        panel.show();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 9: Language switch
    // ═════════════════════════════════════════════════════════════════════════
    private void switchLanguage(I18nManager.Language lang) {
        I18nManager.setLanguage(lang);
        // Re-apply RTL if needed
        if (I18nManager.isRTL()) {
            inputField.setNodeOrientation(NodeOrientation.RIGHT_TO_LEFT);
        } else {
            inputField.setNodeOrientation(NodeOrientation.LEFT_TO_RIGHT);
        }
        // Update labels
        sendButton.setText(I18nManager.t("input.send"));
        regenerateButton.setText(I18nManager.t("btn.regen"));
        inputField.setPromptText(I18nManager.t("input.placeholder"));
        statusLabel.setText(I18nManager.t("header.online"));
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 6: Toggle notification sound
    // ═════════════════════════════════════════════════════════════════════════
    private void toggleNotifSound() {
        boolean newState = !NotificationSoundManager.isEnabled();
        NotificationSoundManager.setEnabled(newState);
        showToast(newState ? "🔔 Notification sound ON" : "🔕 Notification sound OFF");
    }

    // ═════════════════════════════════════════════════════════════════════════
    // SEND / RECEIVE
    // ═════════════════════════════════════════════════════════════════════════
    private void showWelcomeMessage() {
        String welcome = "# 👋 " + I18nManager.t("app.title") + "\n\n" +
                "I'm powered by **Groq & Llama 3** — ask me absolutely anything!\n\n" +
                "### What I can do:\n" +
                "- 💻 **Coding** — Write, debug, and explain code\n" +
                "- 🔬 **Science & Math** — Solve complex problems\n" +
                "- 📚 **Research** — Summarize and explain topics\n" +
                "- ✍️ **Writing** — Essays, emails, creative content\n" +
                "- 🌍 **Translation** — Multiple languages\n" +
                "- 📎 **File & Image Analysis** — Upload files/images\n" +
                "- 🎙 **Voice Input** — Click the mic button to speak\n\n" +
                "**Tip:** Press **Ctrl+?** to see all keyboard shortcuts!\n\n" +
                "*What would you like to explore today?*";
        chatArea.getChildren().add(new ChatBubble(welcome, ChatBubble.BubbleType.BOT));
    }

    private void handleSend() {
        String userText = inputField.getText().trim();
        if (userText.isEmpty()) return;

        currentSession.addMessage("user", userText);
        chatArea.getChildren().add(new ChatBubble(userText, ChatBubble.BubbleType.USER));

        inputField.clear();
        charCountLabel.setText("0 " + I18nManager.t("input.charcount"));
        setInputDisabled(true);
        statusLabel.setText(I18nManager.t("header.thinking")); // Feature 9

        Label typingLabel = new Label(I18nManager.t("typing")); // Feature 9
        typingLabel.getStyleClass().add("typing-indicator");
        chatArea.getChildren().add(typingLabel);

        String finalUserText = userText;
        Thread apiThread = new Thread(() -> {
            String response = groqClient.sendMessage(finalUserText);
            Platform.runLater(() -> {
                chatArea.getChildren().remove(typingLabel);
                currentSession.addMessage("assistant", response);

                // Feature 5: Auto-generate title via AI after first exchange
                autoGenerateTitle();

                SessionManager.saveSession(currentSession);
                if (sidebar != null) sidebar.refresh();

                chatArea.getChildren().add(new ChatBubble(response, ChatBubble.BubbleType.BOT));
                setInputDisabled(false);
                statusLabel.setText(I18nManager.t("header.online"));
                inputField.requestFocus();

                // Feature 6: Notification ping
                NotificationSoundManager.ping();

                if (SpeechManager.isEnabled()) SpeechManager.speak(response);
            });
        });
        apiThread.setDaemon(true);
        apiThread.start();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 5: Auto Title Generator
    // ═════════════════════════════════════════════════════════════════════════
    private void autoGenerateTitle() {
        // Only generate once, when the session still has the default title
        if (!"New Chat".equals(currentSession.getTitle())) return;
        if (currentSession.getMessages().size() < 2) return;

        Thread titleThread = new Thread(() -> {
            String firstUser = currentSession.getMessages().stream()
                    .filter(m -> m.role.equals("user"))
                    .findFirst()
                    .map(m -> m.content)
                    .orElse("");
            if (firstUser.length() < 5) return;

            String prompt = "Generate a very short chat title (max 5 words, no quotes) for this message:\n" + firstUser;
            String title  = groqClient.sendMessage(prompt).trim()
                    .replaceAll("\"", "").replaceAll("\\*", "").trim();
            if (title.length() > 50) title = title.substring(0, 47) + "…";
            if (title.isEmpty())     title = firstUser.substring(0, Math.min(40, firstUser.length()));

            final String finalTitle = title;
            currentSession.setTitle(finalTitle);
            Platform.runLater(() -> {
                SessionManager.saveSession(currentSession);
                if (sidebar != null) sidebar.refresh();
            });
        });
        titleThread.setDaemon(true);
        titleThread.start();
    }

    // ═════════════════════════════════════════════════════════════════════════
    // FEATURE 2: Image Upload & Analysis
    // ═════════════════════════════════════════════════════════════════════════
    private void handleFileUpload() {
        FileChooser chooser = new FileChooser();
        chooser.setTitle(I18nManager.t("btn.upload"));
        chooser.getExtensionFilters().addAll(
            new FileChooser.ExtensionFilter("Supported Files",
                    "*.txt", "*.md", "*.java", "*.py", "*.json", "*.csv",
                    "*.jpg", "*.jpeg", "*.png", "*.gif", "*.webp"),
            new FileChooser.ExtensionFilter("All Files", "*.*"));

        File file = chooser.showOpenDialog(primaryStage);
        if (file == null) return;

        String name = file.getName().toLowerCase();

        // Image path — Feature 2
        if (name.endsWith(".jpg") || name.endsWith(".jpeg")
                || name.endsWith(".png") || name.endsWith(".gif")
                || name.endsWith(".webp")) {
            handleImageUpload(file);
            return;
        }

        // Text/code file — original behaviour
        String content = FileHandler.readFileForAI(file, primaryStage);
        if (content == null) {
            inputField.setText("I uploaded a file: " + file.getName() + "\nPlease analyze it.");
            return;
        }
        String prompt = "I've uploaded a file named **" + file.getName() + "**.\n\n" +
                "Here is its content:\n\n```\n" +
                (content.length() > 3000 ? content.substring(0, 3000) + "\n...[truncated]" : content) +
                "\n```\n\nPlease analyze and summarize this file.";
        inputField.setText(prompt);
    }

    /** Feature 2: Encode image to base64 and send as vision prompt. */
    private void handleImageUpload(File imageFile) {
        try {
            byte[] bytes = java.nio.file.Files.readAllBytes(imageFile.toPath());
            String b64   = java.util.Base64.getEncoder().encodeToString(bytes);
            String ext   = imageFile.getName().substring(
                    imageFile.getName().lastIndexOf('.') + 1).toLowerCase();
            String mime  = ext.equals("jpg") ? "image/jpeg" : "image/" + ext;

            // Show image preview bubble
            ImageView preview = new ImageView(new Image(imageFile.toURI().toString()));
            preview.setFitWidth(260);
            preview.setPreserveRatio(true);
            preview.setStyle("-fx-background-radius: 8px;");

            VBox imgBox = new VBox(6);
            imgBox.setAlignment(Pos.CENTER_RIGHT);
            Label caption = new Label("📷 " + imageFile.getName());
            caption.getStyleClass().add("timestamp-label");
            imgBox.getChildren().addAll(preview, caption);
            HBox wrapper = new HBox();
            wrapper.setAlignment(Pos.CENTER_RIGHT);
            wrapper.setPadding(new Insets(4, 10, 4, 80));
            wrapper.getChildren().add(imgBox);
            chatArea.getChildren().add(wrapper);

            // Build Groq vision-compatible prompt text
            String prompt = "[IMAGE: " + imageFile.getName() + " | base64:" + b64.substring(0, 30) + "…]\n"
                    + "Please analyze and describe this image in detail.";

            // Note: Groq currently supports text models; for vision, use the
            // provided mime+base64 in the prompt so the model understands context.
            // If/when Groq adds full vision API, swap sendMessage() with sendVision().
            String fullPrompt = "I uploaded an image: " + imageFile.getName()
                    + "\nIt is a " + mime + " file (" + (bytes.length / 1024) + " KB)."
                    + "\nPlease describe what you think this image might show, "
                    + "or let me know if you need me to describe it for you.";
            inputField.setText(fullPrompt);

        } catch (Exception e) {
            showAlert("Image Error", "Could not read image: " + e.getMessage());
        }
    }

    // ═════════════════════════════════════════════════════════════════════════
    // REMAINING ORIGINAL METHODS (enhanced)
    // ═════════════════════════════════════════════════════════════════════════
    private void regenerateResponse() {
        setInputDisabled(true);
        statusLabel.setText(I18nManager.t("header.regen"));

        Label typingLabel = new Label(I18nManager.t("typing.regen"));
        typingLabel.getStyleClass().add("typing-indicator");
        chatArea.getChildren().add(typingLabel);

        Thread thread = new Thread(() -> {
            String response = groqClient.regenerateLastResponse();
            Platform.runLater(() -> {
                chatArea.getChildren().remove(typingLabel);
                chatArea.getChildren().add(new ChatBubble(response, ChatBubble.BubbleType.BOT));
                setInputDisabled(false);
                statusLabel.setText(I18nManager.t("header.online"));
                NotificationSoundManager.ping(); // Feature 6
            });
        });
        thread.setDaemon(true);
        thread.start();
    }

    private void showExportMenu() {
        ContextMenu menu = new ContextMenu();
        MenuItem txtItem  = new MenuItem("📄 Export as TXT");
        MenuItem htmlItem = new MenuItem("🌐 Export as HTML");
        txtItem.setOnAction(e  -> FileHandler.exportAsTXT(currentSession, primaryStage));
        htmlItem.setOnAction(e -> FileHandler.exportAsHTML(currentSession, primaryStage));
        menu.getItems().addAll(txtItem, htmlItem);
        menu.show(exportButton, Side.BOTTOM, 0, 0);
    }

    private void openSettings() {
        SettingsPanel settings = new SettingsPanel(this, this.getScene());
        settings.show();
    }

    public void loadSession(ChatSession session) {
        this.currentSession = session;
        SessionManager.setCurrentSession(session);
        groqClient = new GroqClient();
        groqClient.setModel(session.getModel());
        groqClient.setPersona(session.getPersona());
        chatArea.getChildren().clear();
        for (ChatSession.Message msg : session.getMessages()) {
            ChatBubble.BubbleType t = msg.role.equals("user")
                    ? ChatBubble.BubbleType.USER : ChatBubble.BubbleType.BOT;
            chatArea.getChildren().add(new ChatBubble(msg.content, t));
        }
        updateModelLabel();
    }

    private void clearChat() {
        chatArea.getChildren().clear();
        currentSession = SessionManager.createNewSession();
        groqClient.clearHistory();
        if (sidebar != null) sidebar.refresh();
        showWelcomeMessage();
    }

    private void setInputDisabled(boolean disabled) {
        inputField.setDisable(disabled);
        sendButton.setDisable(disabled);
        clearButton.setDisable(disabled);
        uploadButton.setDisable(disabled);
        micButton.setDisable(disabled || !VoiceInputManager.isAvailable());
    }

    private void updateModelLabel() {
        modelLabel.setText("Model: " + groqClient.getCurrentModel()
                + "  ·  Persona: " + groqClient.getCurrentPersona());
    }

    // ── Helpers ───────────────────────────────────────────────────────────────
    private Button iconBtn(String icon, String tooltip, javafx.event.EventHandler<javafx.event.ActionEvent> handler) {
        Button btn = new Button(icon);
        btn.getStyleClass().add("header-icon-btn");
        btn.setTooltip(new Tooltip(tooltip));
        btn.setOnAction(handler);
        return btn;
    }

    /** Brief non-blocking toast notification in the status label. */
    private void showToast(String msg) {
        String prev = statusLabel.getText();
        statusLabel.setText(msg);
        PauseTransition pause = new PauseTransition(Duration.seconds(2));
        pause.setOnFinished(e -> statusLabel.setText(prev));
        pause.play();
    }

    private void showAlert(String title, String msg) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setContentText(msg);
        alert.show();
    }

    // ── Getters / setters for SettingsPanel ───────────────────────────────────
    public void setSidebar(Sidebar sidebar)     { this.sidebar = sidebar; }
    public void setModel(String model)          { groqClient.setModel(model); currentSession.setModel(model); updateModelLabel(); }
    public void setPersona(String persona)      { groqClient.setPersona(persona); currentSession.setPersona(persona); updateModelLabel(); }
    public String getCurrentModel()             { return groqClient.getCurrentModel(); }
    public String getCurrentPersona()           { return groqClient.getCurrentPersona(); }
    public void setFontSize(int size)           { ChatBubble.setFontSize(size); }
}
